name: "Deploy"

on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Install node.js"
        uses: actions/setup-node@v4
        with:
            node-version: "21"

      - name: "Checkout code"
        uses: actions/checkout@v4
 
      - name: "Install dependencies"
        run: npm install

      - name: "Run the tests"
        run: npm test